const array = [0, 1, 2, 3, 4, 5];
array.push(11);
console.log(array);
const res1 = array.pop();
console.log(res1);
console.log(array);
const res2 = array.shift();
console.log(res2);
console.log(array);
array.unshift(20);
console.log(array);
const res3 = array.splice(3, 2);
console.log(res3);
console.log(array);
const res4 = [res1, ...array, ...res3];
console.log(res4);
console.log(array);
const res5 = array.concat(res4, res1);
console.log(res5);
console.log(array);
